---
#-------------------------------
# Site Settings
title: SHEFFmachine
logo: '/images/JeremyLogoLight.png' # You can add own logo. For example '/images/logo.png'.
logo_dark: '/images/JeremyLogoDark.png'
description: Principal Engineer in Fintech.
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.

#-------------------------------
# Navigation Settings
menu_settings:
  menu_items:
    - title: 'Home'
      url: '/'
    - title: 'Career'
      url: '/career/'
    - title: 'Blog'
      url: '/blog/'
    - title: 'About'
      url: '/about/'
    - title: 'Contact'
      url: '/contact/'
    # - title: 'Pages'
    #   submenu:
    #     - url: '/elements/'
    #       title: 'Elements'

#-------------------------------
# Author Settings
author:
  author_name: Jeremy Shefer
  author_avatar: '/images/JeremyAvatar.JPG'

#-------------------------------
# Hero Settings
hero:
  enable: true
  hero_role: Principal Engineer ∙ Former CPA ∙ New Father
  hero_title: Hi! I’m Jeremy <img src="/images/JeremyAvatar.JPG" alt="Jeremy Shefer Picture" loading="lazy"> <br> I solve fintech problems with software.
  hero_description: I combine over 10 years in software with my background in accounting & finance into an exciting career.
  # hero_button_text: Let's explore software together!
  # hero_button_link: '/blog/'

#-------------------------------
# Projects Section Settings
projects:
  enable: false
  projects_title: Selected Works
  projects_description: This series celebrates cultural diversity and heritage through intricate, detailed designs. Drawing inspiration from various cultures and traditions, I create artworks that tell stories of identity and community. The pieces are rich in symbolism and patterns, offering a deep, visual narrative. By honoring cultural histories, the series fosters a sense of connection and appreciation for global diversity.

#-------------------------------
# Testimonials Section Settings
testimonials:
  enable: false
  testimonials_title: What People Say?
  testimonials_description: Hear from those who have experienced the transformative power of my artistry and design. These testimonials showcase the success stories born from our collaborative partnerships.
  testimonials_info: Loved by 50+ customers
  testimonial_items:
    - name: 'John Smith'
      image: '/images/client-1.jpg'
      designation: 'CEO of Creative Innovations'
      content: "Collaborating was a seamless experience. The creativity and execution brought our project to life in ways we couldn't have imagined."

    - name: 'David Wilson'
      image: '/images/client-2.jpg'
      designation: 'Senior Designer at Elegance Studios'
      content: 'The elegant and modern design aesthetic was exactly what we needed. The work was both inspiring and flawlessly executed.'

    - name: 'Sarah Davis'
      image: '/images/client-3.jpg'
      designation: 'Director of FutureTech Labs'
      content: 'The blend of technology and art was masterful. Every piece showcased a deep understanding of both disciplines.'

#-------------------------------
# Blog Section Settings
blog:
  enable: true
  blog_title: SHEFFblog
  blog_description: Dive into a world of fintech from both product and engineering angles.

#-------------------------------
# About Section Settings
about:
  enable: true
  about_image: '/images/JeremyTea.JPG'
  about_title: Short Story About Me
  about_description: I grew up on the lap of my grandfather, listening to his epic hydraulic engineering stories.  After watching the adults grapple with the 1998 Russian Financial Crisis, I got interested in finance and economics as well. The rest is in my career section.
  about_button_text: See my full career path
  about_button_link: '/career/'

#-------------------------------
# Career Section Settings
career:
  enable: true

#-------------------------------
# Faq (Frequently asked questions) Settings
faq:
  enable: true
  faq_title: Need Some Answers?
  faq_description:
  faq_items:
    - title: What is your current gig?
      description: I am a Principal Software Engineer at Avant.
    - title: How did you transition from accounting / finance?
      description: I spent almost a year nights and weekends after work, and am entirely self taught. I used C++ and Cocos2dx as my first language to make video games (Birdclash, powder puff and others), and web technoligies to make the website for the games. I then tried to launch an e-commerce website from scratch (think task rabbit meets craigslist). After all that failed I moved myself to SF Bay Area and the rest is history.
    - title: What are your interests in programming?
      description: I like playing around with various frameworks and languages, testing and tracing tools, machine learning and data science tools to test their performance and usability. Really their suitability for real world business use cases.
    - title: What are your interests outside of programming?
      description: Parenting, biking, tennis and Jewish Learning.
    - title: What is the best language?
      description: Python because of its tooling, async web frameworks, pandas, keras and much much more.

#-------------------------------
# Newsletter Settings
mailchimp:
  enable: false
  mailchimp_title: Stay inspired weekly. Your friendly dose of tips & insights!
  mailchimp_description: Every Sunday, I deliver actionable tips for enhancing productivity, practical life advice, and top-notch insights gathered from various sources, right to your email inbox.
  mailchimp_identifier: gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp # Add your MailChimp form identifier. For example - gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp
  mailchimp_input_text: Your email address...
  mailchimp_button_text: Subscribe
  mailchimp_background_image: '/images/subscribe-bg.jpg'

#-------------------------------
# Social Links
social:
  # - {
  #     icon: 'fa-brands fa-youtube',
  #     name: 'Youtube',
  #     link: 'https://youtube.com',
  #   }
  - {
      icon: 'fa-brands fa-linkedin',
      name: 'Linked In',
      link: 'https://www.linkedin.com/in/jeremyshefer/',
    }
  # - { icon: 'fa-brands fa-medium', name: 'Medium', link: 'https://medium.com' }
  - {
      icon: 'fa-brands fa-github',
      name: 'Github',
      link: 'https://github.com/SHEFFcode',
    }
  - {
      icon: 'cib-leetcode',
      name: 'Github',
      link: 'https://github.com/SHEFFcode',
    }

# Example of adding a new link to the footer - {icon: "fa-brands fa-mastodon", name: "Mastodon", link: "https://mastodon.social"}
# Other icons can be found at https://fontawesome.com/icons

#-------------------------------
# Contact Settings
contact:
  contact_email: jeremy@sheffmachine.com # Add your form_id
  contact_button_text: Send Message

# NOTE
# Renva theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.

#-------------------------------
# Comment Section (Disqus)
disqus-identifier: anvod-studio-test # Add your shortname for Disqus Comment. For example anvod-studio-test

#-------------------------------
# Google Analytics
google-analytics: # Add your GA Tracking Id
